### ISSUE TITLE
🐛 [Bug]: 运行tiny bulid时提示 没有 @opentiny/tiny-plugin-bulid 且无法找到安装方法

### ISSUE THREAD

**Issue by alexblair** [opentiny/tiny-cli#105]
### Version

tiny v1.1.0

### node-version

v16.20.2

### Link to minimal reproduction

执行 tiny bulid  时，提示 [core-commands]: @opentiny/tiny-plugin-bulid 插件不存在，请确认套件名称或npm源是否正确 
无法进行 项目的 打包和发布。

### Step to reproduce

 tiny bulid

### What is expected

正常bulid 并且在目录下生成正确的 HTML页面。

### What is actually happening

``tiny bulid`` 
系统提示：
2023-09-20 19:02:42 [core-commands]: @opentiny/tiny-plugin-bulid 插件不存在，请确认套件名称或npm源是否正确 

尝试手工安装时：
``tiny i @opentiny/tiny-plugin-bulid ``

无法安装

**Install fail! Error: GET https://registry.npmmirror.com/@opentiny%2Ftiny-plugin-bulid response 404 status**

Error: GET https://registry.npmmirror.com/@opentiny%2Ftiny-plugin-bulid response 404 status
    at get (/usr/lib/node_modules/@opentiny/cli/node_modules/npminstall/lib/get.js:69:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _fetchFullPackageMeta (/usr/lib/node_modules/@opentiny/cli/node_modules/npminstall/lib/download/npm.js:267:18)
    at async _fetchFullPackageMetaWithCache (/usr/lib/node_modules/@opentiny/cli/node_modules/npminstall/lib/download/npm.js:210:14)
    at async getFullPackageMeta (/usr/lib/node_modules/@opentiny/cli/node_modules/npminstall/lib/download/npm.js:194:12)
    at async resolve (/usr/lib/node_modules/@opentiny/cli/node_modules/npminstall/lib/download/npm.js:47:24)
    at async module.exports (/usr/lib/node_modules/@opentiny/cli/node_modules/npminstall/lib/download/npm.js:22:19)
    at async module.exports (/usr/lib/node_modules/@opentiny/cli/node_modules/npminstall/lib/download/index.js:19:10)
    at async _install (/usr/lib/node_modules/@opentiny/cli/node_modules/npminstall/lib/install_package.js:122:16)
    at async install (/usr/lib/node_modules/@opentiny/cli/node_modules/npminstall/lib/install_package.js:23:12)
npminstall version: 7.10.0
npminstall argv: /usr/bin/node /usr/lib/node_modules/@opentiny/cli/node_modules/npminstall/bin/install.js @opentiny/tiny-plugin-bulid --stdio=inherit --registry=https://registry.npmmirror.com/ --cwd=/alexblair/windir/www/alexblair_synology_me/test/tiny/tiny-pro --china --dependencies-tree=/alexblair/windir/www/alexblair_synology_me/test/tiny/tiny-pro/package-lock.json --save-dependencies-tree

### Any additional comments (optional)

几个建议：
1、提供 bulid的正常使用方法。这个很关键。

2、 tiny i 安装时，原因时调用NPM时没有找到安装源 出现 404.  但是在提示中，给出了非常恐怖的
“为了保证项目稳定性，请删除本地失败的node_modules后再重试。可执行命令: rm -rf node_modules” 
对于小白用户，或者复杂项目，这个操作是灾难性的。**请不要**再这样提示用户了。

**Comment by fengyon** [comment]
感谢您的反馈，经过排查，我们没有发布build插件
请先使用`npm run build` 进行打包
我们会尽快排查与修复此问题

**Comment by fengyon** [comment]
经过仔细观察，发现是您的单词拼错了，是`build`，而非 "bu**lid**"

**Comment by fengyon** [comment]
感谢您提出的第二个建议，但是我们暂时不会采纳。
主要有以下原因：
1、安装依赖失败可能会导致问题，在某些情况下需要删除所有已安装的依赖重新安装，因此提示是有必要的。至于需不需要删除node_modules重新安装，需要用户自己考虑。
一般来说，如果是还没开始安装依赖（指还没有生成依赖文件）就失败了，可以不删除已安装依赖；如果某个依赖安装到一半（指生成了部分依赖文件）失败了，需要删除已安装依赖后再重新安装。

2、删除本地的node_modules一般来说是没有什么风险的，因为现在开发一般是克隆项目的核心代码(不含`node_modules`)，再执行`npm i`生成`node_modules`，不会将node_modules 上传至代码仓。
删除`node_modules`后，重新执行项目的初始化命令即可（`npm i`或者其他）

**Comment by alexblair** [comment]
感谢反馈，目前问题正常。
解决方案为：
1、tiny update 各组件
2、执行 bulid ，运行正常没有报错。
