### ISSUE TITLE
🐛 [Bug]: tiny v1.0.1 执行 tiny init pro 命令报错 

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-cli#36]
### Version

v1.0.1

### node-version

v16.18.0

### Step to reproduce

执行以下命令
```
tiny init pro
```

报以下错：
```
$ tiny init pro
2023-05-17 23:35:04 [core-module]: 本地尚未安装 @opentiny/tiny-toolkit-pro ,正在执行自动安装... 
✖ Install fail! Error: GET https://registry.npmjs.org/@opentiny%2Ftiny-toolkit-vue-pro response 404 status
Error: GET https://registry.npmjs.org/@opentiny%2Ftiny-toolkit-vue-pro response 404 status
    at get (/usr/local/lib/node_modules/npminstall/lib/get.js:68:17)
    at get.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/npminstall/node_modules/co/index.js:65:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
npminstall version: 3.28.1
npminstall args: /usr/local/bin/node /usr/local/bin/npminstall --cwd=/.tiny --stdio=inherit --registry=https://registry.npmjs.org/ --china --dependencies-tree=/code/temp/tiny-cli-demo3/package-lock.json --save-dependencies-tree
2023-05-17 23:35:08 [core-module]: @opentiny/tiny-toolkit-pro 安装报错，请确认该package是否存在! 
2023-05-17 23:35:08 [core-module]: Error: 安装  失败！为了保证项目稳定性，请删除本地失败的node_modules后再重试。可执行命令: rm -rf node_modules
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@opentiny/cli/node_modules/@opentiny/cli-devkit/lib/npm/index.js:228:24)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12) 
```

**Comment by fengyon** [comment]
感谢您的反馈，正在排查此问题

**Comment by kagol** [comment]
> 感谢您的反馈，正在排查此问题

@fengyon 请问这个有进展吗？我这边是 macOS 12.2 操作系统，node版本是 v16.18.0，如果还需要提供其他信息，请及时告知

**Comment by kagol** [comment]
@fengyon 我尝试执行 `tiny init vue-pro` 也是不行的，报以下错误：

$ tiny init vue-pro
2023-06-07 19:39:25 [core-commands]: @opentiny/tiny-toolkit-vue-pro 套件不存在，请确认套件名称或npm源是否正确

配置的 registry 如下：
```
registry=https://registry.npmjs.org/
```

**Comment by cangkui** [comment]
+1。node版本试过18.11.0和16.13.0，都是在安装完毕tiny-cli之后使用`tiny init pro`时报模块`@opentiny/cli-devkit`不存在的问题。使用`tiny init`命令并且选择`dev`套件时，报`del`模块找不到的问题，并且这些模块找不到问题在使用`npm i 模块名 -g`安装缺失模块后仍然无法解决。

**Comment by cangkui** [comment]
> +1。node版本试过18.11.0和16.13.0，都是在安装完毕tiny-cli之后使用`tiny init pro`时报模块`@opentiny/cli-devkit`不存在的问题。使用`tiny init`命令并且选择`dev`套件时，报`del`模块找不到的问题，并且这些模块找不到问题在使用`npm i 模块名 -g`安装缺失模块后仍然无法解决。

具体报错如下：
```
λ tiny init
? 请选择一个适合您项目的套件进行初始化:   pro  ----------  开箱即用的中后台前端/设计解决方案
2023-06-24 10:03:29 [core-error]: 运行插件或套件时出现了错误, 未找到 @opentiny/cli-devkit 模块! 正在尝试自动修复...
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: Cannot find module '@opentiny/cli-devkit'
Require stack:
- C:\Users\GORDEN\.tiny\node_modules\_@opentiny_tiny-toolkit-pro@1.0.6@@opentiny\tiny-toolkit-pro\dist\lib\start.js
- C:\Users\GORDEN\.tiny\node_modules\_@opentiny_tiny-toolkit-pro@1.0.6@@opentiny\tiny-toolkit-pro\dist\index.js
- D:\Tools\nvm\v16.13.0\node_modules\@opentiny\cli\node_modules\@opentiny\cli-devkit\lib\module\get.js
- D:\Tools\nvm\v16.13.0\node_modules\@opentiny\cli\node_modules\@opentiny\cli-devkit\lib\module\index.js
- D:\Tools\nvm\v16.13.0\node_modules\@opentiny\cli\node_modules\@opentiny\cli-devkit\lib\index.js
- D:\Tools\nvm\v16.13.0\node_modules\@opentiny\cli\lib\config.js
- D:\Tools\nvm\v16.13.0\node_modules\@opentiny\cli\lib\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (D:\Tools\nvm\v16.13.0\node_modules\@opentiny\cli\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\GORDEN\.tiny\node_modules\_@opentiny_tiny-toolkit-pro@1.0.6@@opentiny\tiny-toolkit-pro\dist\lib\start.js:27:22)
    at Module._compile (D:\Tools\nvm\v16.13.0\node_modules\@opentiny\cli\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\GORDEN\\.tiny\\node_modules\\_@opentiny_tiny-toolkit-pro@1.0.6@@opentiny\\tiny-toolkit-pro\\dist\\lib\\start.js',
    'C:\\Users\\GORDEN\\.tiny\\node_modules\\_@opentiny_tiny-toolkit-pro@1.0.6@@opentiny\\tiny-toolkit-pro\\dist\\index.js',
    'D:\\Tools\\nvm\\v16.13.0\\node_modules\\@opentiny\\cli\\node_modules\\@opentiny\\cli-devkit\\lib\\module\\get.js',
    'D:\\Tools\\nvm\\v16.13.0\\node_modules\\@opentiny\\cli\\node_modules\\@opentiny\\cli-devkit\\lib\\module\\index.js',
    'D:\\Tools\\nvm\\v16.13.0\\node_modules\\@opentiny\\cli\\node_modules\\@opentiny\\cli-devkit\\lib\\index.js',
    'D:\\Tools\\nvm\\v16.13.0\\node_modules\\@opentiny\\cli\\lib\\config.js',
    'D:\\Tools\\nvm\\v16.13.0\\node_modules\\@opentiny\\cli\\lib\\index.js'
  ]
}
```
以及
```
λ tiny init
? 请选择一个适合您项目的套件进行初始化:   dev  ----------  开发tiny-cli套件和插件
2023-06-24 10:07:10 [core-module]: 本地尚未安装 @opentiny/tiny-toolkit-dev ,正在执行自动安装...
npminstall WARN load dependencies tree D:\Projects\Node.js Project\tiny-pro-vue\package-lock.json error: ENOENT: no such file or directory, open 'D:\Projects\Node.js Project\tiny-pro-vue\package-lock.json'
√ Installed 2 packages
√ Linked 45 latest versions
√ Run 0 scripts
deprecate @opentiny/tiny-toolkit-dev@1.0.1 › axios@^0.19.0 Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
deprecate @opentiny/tiny-toolkit-dev@1.0.1 › @lerna/create-symlink@3.16.2 › @zkochan/cmd-shim@3.1.0 › mkdirp-promise@^5.0.1 This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
√ All packages installed (27 packages installed from npm registry, used 10s(network 10s), speed 287.78kB/s, json 47(1.8MB), tarball 985.33kB)
2023-06-24 10:07:24 [core-module]: @opentiny/tiny-toolkit-dev 安装成功
2023-06-24 10:07:25 [core-error]: 运行插件或套件时出现了错误, 未找到 del 模块! 正在尝试自动修复...
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: Cannot find module 'del'
Require stack:
- C:\Users\GORDEN\.tiny\node_modules\_@opentiny_cli-devkit@1.0.1@@opentiny\cli-devkit\lib\home\index.js
- C:\Users\GORDEN\.tiny\node_modules\_@opentiny_cli-devkit@1.0.1@@opentiny\cli-devkit\lib\log\index.js
- C:\Users\GORDEN\.tiny\node_modules\_@opentiny_cli-devkit@1.0.1@@opentiny\cli-devkit\lib\argv\index.js
- C:\Users\GORDEN\.tiny\node_modules\_@opentiny_cli-devkit@1.0.1@@opentiny\cli-devkit\lib\index.js
- C:\Users\GORDEN\.tiny\node_modules\_@opentiny_tiny-toolkit-dev@1.0.1@@opentiny\tiny-toolkit-dev\dist\lib\init.js
- C:\Users\GORDEN\.tiny\node_modules\_@opentiny_tiny-toolkit-dev@1.0.1@@opentiny\tiny-toolkit-dev\dist\index.js
- D:\Tools\nvm\v16.13.0\node_modules\@opentiny\cli\node_modules\@opentiny\cli-devkit\lib\module\get.js
- D:\Tools\nvm\v16.13.0\node_modules\@opentiny\cli\node_modules\@opentiny\cli-devkit\lib\module\index.js
- D:\Tools\nvm\v16.13.0\node_modules\@opentiny\cli\node_modules\@opentiny\cli-devkit\lib\index.js
- D:\Tools\nvm\v16.13.0\node_modules\@opentiny\cli\lib\config.js
- D:\Tools\nvm\v16.13.0\node_modules\@opentiny\cli\lib\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (D:\Tools\nvm\v16.13.0\node_modules\@opentiny\cli\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\GORDEN\.tiny\node_modules\_@opentiny_cli-devkit@1.0.1@@opentiny\cli-devkit\lib\home\index.js:44:26)
    at Module._compile (D:\Tools\nvm\v16.13.0\node_modules\@opentiny\cli\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\GORDEN\\.tiny\\node_modules\\_@opentiny_cli-devkit@1.0.1@@opentiny\\cli-devkit\\lib\\home\\index.js',
    'C:\\Users\\GORDEN\\.tiny\\node_modules\\_@opentiny_cli-devkit@1.0.1@@opentiny\\cli-devkit\\lib\\log\\index.js',
    'C:\\Users\\GORDEN\\.tiny\\node_modules\\_@opentiny_cli-devkit@1.0.1@@opentiny\\cli-devkit\\lib\\argv\\index.js',
    'C:\\Users\\GORDEN\\.tiny\\node_modules\\_@opentiny_cli-devkit@1.0.1@@opentiny\\cli-devkit\\lib\\index.js',
    'C:\\Users\\GORDEN\\.tiny\\node_modules\\_@opentiny_tiny-toolkit-dev@1.0.1@@opentiny\\tiny-toolkit-dev\\dist\\lib\\init.js',
    'C:\\Users\\GORDEN\\.tiny\\node_modules\\_@opentiny_tiny-toolkit-dev@1.0.1@@opentiny\\tiny-toolkit-dev\\dist\\index.js',
    'D:\\Tools\\nvm\\v16.13.0\\node_modules\\@opentiny\\cli\\node_modules\\@opentiny\\cli-devkit\\lib\\module\\get.js',
    'D:\\Tools\\nvm\\v16.13.0\\node_modules\\@opentiny\\cli\\node_modules\\@opentiny\\cli-devkit\\lib\\module\\index.js',
    'D:\\Tools\\nvm\\v16.13.0\\node_modules\\@opentiny\\cli\\node_modules\\@opentiny\\cli-devkit\\lib\\index.js',
    'D:\\Tools\\nvm\\v16.13.0\\node_modules\\@opentiny\\cli\\lib\\config.js',
    'D:\\Tools\\nvm\\v16.13.0\\node_modules\\@opentiny\\cli\\lib\\index.js'
  ]
}
```
在全局安装完缺失模块后仍然报上述错误。

**Comment by wjiangwang** [comment]
> @fengyon 我尝试执行 `tiny init vue-pro` 也是不行的，报以下错误：
> 
> $ tiny init vue-pro 2023-06-07 19:39:25 [core-commands]: @opentiny/tiny-toolkit-vue-pro 套件不存在，请确认套件名称或npm源是否正确
> 
> 配置的 registry 如下：
> 
> ```
> registry=https://registry.npmjs.org/
> ```
 `tiny init vue-pro` 命令已经废弃，套件名称为@opentiny/tiny-toolkit-pro，套件的最新版本已发布
建议先执行`tiny clear`命令清除缓存  ，再执行`tiny init pro` 尝试

**Comment by wjiangwang** [comment]
@cangkui  套件已发布最新版本，建议先执行`tiny clear`命令清除缓存 ，再执行`tiny init pro` 命令尝试

**Comment by kagol** [comment]
> @cangkui 套件已发布最新版本，建议先执行`tiny clear`命令清除缓存 ，再执行`tiny init pro` 命令尝试

为什么要让开发者执行这个 tiny clear 命令呢？

**Comment by phoenixor** [comment]
都2026年了这个bug还没修复也是醉了，tiny版本1.1.1，node 24.15.0
