### ISSUE TITLE
tiny init 报错

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [opentiny/tiny-cli#78]
### Version

tiny v1.1.0

### node-version

v18.16.0

### Step to reproduce

os
```sh
$ uname -a
Linux hp 6.1.38-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Jul  5 23:49:30 UTC 2023 x86_64 GNU/Linux
```

nvm

```sh
$ nvm ls                  
->     v18.16.0
default -> stable (-> v18.16.0)
iojs -> N/A (default)
unstable -> N/A (default)
node -> stable (-> v18.16.0) (default)
stable -> 18.16 (-> v18.16.0) (default)
lts/* -> lts/fermium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.1 (-> N/A)
lts/erbium -> v12.22.3 (-> N/A)
lts/fermium -> v14.17.3 (-> N/A)
```

git

```sh
$ git --version
git version 2.41.0
```

install cli
```sh
npm install @opentiny/cli npminstall@3 -g
```

```sh
$ tiny init
/home/mmc/.nvm/versions/node/v18.16.0/lib/node_modules/@opentiny/cli/node_modules/ping/lib/parser/mac.js:42
        this._times.push(parseFloat(match[1], 10));
                                         ^

TypeError: Cannot read properties of null (reading '1')
    at MacParser._processBody (/home/mmc/.nvm/versions/node/v18.16.0/lib/node_modules/@opentiny/cli/node_modules/ping/lib/parser/mac.js:42:42)
    at LinuxParser._processBody (/home/mmc/.nvm/versions/node/v18.16.0/lib/node_modules/@opentiny/cli/node_modules/ping/lib/parser/linux.js:45:38)
    at parser.eat (/home/mmc/.nvm/versions/node/v18.16.0/lib/node_modules/@opentiny/cli/node_modules/ping/lib/parser/base.js:133:14)
    at /home/mmc/.nvm/versions/node/v18.16.0/lib/node_modules/@opentiny/cli/node_modules/underscore/underscore-node-f.cjs:716:19
    at Function.each (/home/mmc/.nvm/versions/node/v18.16.0/lib/node_modules/@opentiny/cli/node_modules/underscore/underscore-node-f.cjs:1323:7)
    at ChildProcess.<anonymous> (/home/mmc/.nvm/versions/node/v18.16.0/lib/node_modules/@opentiny/cli/node_modules/ping/lib/ping-promise.js:83:12)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)

Node.js v18.16.0
```

### What is expected

tiny init works fine

### What is actually happening

![image](https://github.com/opentiny/tiny-cli/assets/7458713/a08dee4e-6540-447d-a942-41635afb7258)

**Comment by aliceDxr** [comment]
node版本切换16试试 ~

**Comment by ziyouchutuwenwu** [comment]
装完16.0.0和16.2.1也都不行，这是16.0.0的结果

```sh
tiny init
/home/mmc/.nvm/versions/node/v16.0.0/lib/node_modules/@opentiny/cli/node_modules/ping/lib/parser/mac.js:42
        this._times.push(parseFloat(match[1], 10));
                                         ^

TypeError: Cannot read property '1' of null
    at LinuxParser.MacParser._processBody (/home/mmc/.nvm/versions/node/v16.0.0/lib/node_modules/@opentiny/cli/node_modules/ping/lib/parser/mac.js:42:42)
    at LinuxParser._processBody (/home/mmc/.nvm/versions/node/v16.0.0/lib/node_modules/@opentiny/cli/node_modules/ping/lib/parser/linux.js:45:38)
    at LinuxParser.parser.eat (/home/mmc/.nvm/versions/node/v16.0.0/lib/node_modules/@opentiny/cli/node_modules/ping/lib/parser/base.js:133:14)
    at /home/mmc/.nvm/versions/node/v16.0.0/lib/node_modules/@opentiny/cli/node_modules/underscore/underscore-node-f.cjs:716:19
    at Function.each (/home/mmc/.nvm/versions/node/v16.0.0/lib/node_modules/@opentiny/cli/node_modules/underscore/underscore-node-f.cjs:1323:7)
    at ChildProcess.<anonymous> (/home/mmc/.nvm/versions/node/v16.0.0/lib/node_modules/@opentiny/cli/node_modules/ping/lib/ping-promise.js:83:12)
    at Object.onceWrapper (node:events:472:26)
    at ChildProcess.emit (node:events:365:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

**Comment by aliceDxr** [comment]
能不能试下 手动升级ping包      /usr/local/node_modules/@opentiny/cli   执行npm i ping

**Comment by ziyouchutuwenwu** [comment]
我是nvm装的，必须要在 /usr/local/node_modules下面？
![image](https://github.com/opentiny/tiny-cli/assets/7458713/e2b41730-5c7d-42b5-b1c1-be1c854666f1)

**Comment by ziyouchutuwenwu** [comment]
还是报错，步骤如下
![image](https://github.com/opentiny/tiny-cli/assets/7458713/6dcb79d2-5581-4923-b974-2f239c97282a)
![image](https://github.com/opentiny/tiny-cli/assets/7458713/51b5c4d5-9da4-41f4-b3b5-e522112579b6)

运行
![image](https://github.com/opentiny/tiny-cli/assets/7458713/b33d979c-c35a-425a-884f-cdafe7ff7518)

**Comment by aliceDxr** [comment]
tiny-cli暂时不支持Linux系统  可以在windows和mac使用

**Comment by ziyouchutuwenwu** [comment]
ok
